DATA_PATH: ./dataset
FLOWER_SSL_CACERT: ./certificates
SANDBOX_PATH: ./sandbox
data_file: 3362-2045-1944.parquet
data_path: dataset/
dataset: youthgems_format
dropout:
  percentage_drop: 50
dropout_method: None
experiment:
  debug: true
  log_path: logs
  name: experiment_1
feature_subset:
- ADBWGT00
- FCSTYY00
- ECHTCMA0
- ECWTCMA0
- ECBFPC00
- EMCS5AGE
- EBMIN5
- FDKESSL
- FCWTCM00
- FCBFPC00
- FCHTCM00
- FCSTYU00
- FCPTNT00
- FCSCWK00
- FCWYLK00
- FCFMLY00
- FCFRNS00
- FCSCHL00
- FCLIFE00
- FCRISK00
- FCTRST0A
- ECQ10A00
- ECQ10B00
- ECQ10C00
- ECQ10D00
- ECQ10E00
- ECQ10F00
- MCSID
- ACNUM00
- Eval
held_out_center_id: -1
linear_models:
  n_features: 9
local_port: 8081
metadata_file: metadata.json
model: random_forest
normalization_method: IQR
num_clients: 2
num_rounds: 3
outcome: Eval
production_mode: false
random_forest:
  balanced_rf: true
seed: 42
smoothWeights:
  smoothing_strenght: 0.5
smooth_method: None
target_label:
- Eval
train_size: 0.7
weighted_random_forest:
  balanced_rf: true
  levelOfDetail: DecisionTree
xgb:
  batch_size: 32
  num_iterations: 100
  task_type: BINARY
  tree_num: 500
